### ISSUE TITLE
It no longer works

### ISSUE THREAD

**Issue by ducfilan** [purplegrapeZz/goroutine-py#2]
I ran your `demo.py` but it only outputs `END` without running other goroutines.

**Comment by purplegrapeZz** [comment]
print "END" first is expected. You can show the codes here.

**Comment by purplegrapeZz** [comment]
You can use command "python -i demo.py" which can run the demo without close the thread so that can see the output.

**Comment by purplegrapeZz** [comment]
This lib run with concurrent services works better like a Wed Server  but no single file.
